### ISSUE TITLE
How to change the range of accelerometer and gyroscope on the sketch of Ardunio IDE?

### ISSUE THREAD

**Issue by R-Himanshu** [DFRobot/DFRobot_BMI160#3]
I have been trying understand and write a code for changing the sensitivity and data rate of BMI160 for both accelerometer and gyroscope.

**Comment by Arya11111** [comment]
Sorry, this library does not have this function, if you want to modify it, you can read its datasheet to config : https://www.dfrobot.com.cn/images/upload/File/20180420182442v6gvv1.pdf
